# Generated by Django 5.1.15 on 2026-06-13 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('executed', 'Executed'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'is_archived'], name='campaigns_c_organiz_d749c6_idx'),
        ),
    ]
