# Generated by Django 5.1.15 on 2026-06-22 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0004_mediaasset"),
        ("crm", "0002_contactgroup"),
        ("organizations", "0004_alter_organization_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="contact_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="crm.contactgroup",
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="components",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="examples",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="meta_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="quality_rating",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="rejected_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="template_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_media_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="media_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="templates",
                to="campaigns.mediaasset",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization", "asset_type"],
                name="campaigns_m_organiz_b32ffc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mediaasset",
            index=models.Index(
                fields=["organization", "created_at"],
                name="campaigns_m_organiz_c34ff6_idx",
            ),
        ),
    ]
