# Generated by Django 5.1.15 on 2026-07-25 15:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_campaign_click_events"),
        ("organizations", "0006_organization_access_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ECardClick",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ECardTrackedLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=255)),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("destination_url", models.URLField(max_length=1000)),
                ("template_name", models.CharField(blank=True, max_length=255)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="campaignclickevent",
            new_name="campaigns_c_organiz_43f87d_idx",
            old_name="campaigns_c_organiz_7f2a91_idx",
        ),
        migrations.RenameIndex(
            model_name="campaignclickevent",
            new_name="campaigns_c_organiz_0bd7d9_idx",
            old_name="campaigns_c_organiz_4c8b12_idx",
        ),
        migrations.AlterField(
            model_name="campaignclickevent",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="ecardclick",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="ecardtrackedlink",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ecard_tracked_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ecardtrackedlink",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="ecardclick",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="campaigns.ecardtrackedlink",
            ),
        ),
        migrations.AddIndex(
            model_name="ecardtrackedlink",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="campaigns_e_organiz_ac0f48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecardtrackedlink",
            index=models.Index(
                fields=["organization", "phone"], name="campaigns_e_organiz_abb88f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecardtrackedlink",
            index=models.Index(
                fields=["organization", "-last_clicked_at"],
                name="campaigns_e_organiz_574346_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecardclick",
            index=models.Index(
                fields=["organization", "-clicked_at"],
                name="campaigns_e_organiz_f870c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecardclick",
            index=models.Index(
                fields=["organization", "phone"], name="campaigns_e_organiz_497d65_idx"
            ),
        ),
    ]
