# Generated by Django 5.1.15 on 2026-06-20 10:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("organizations", "0004_alter_organization_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=20, unique=True)),
                ("seats", models.IntegerField(default=1)),
                ("channels", models.IntegerField(default=1)),
                ("monthly_free_conversations", models.IntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ConversationCharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wa_conversation_id", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utility"),
                            ("authentication", "Authentication"),
                            ("service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("country_code", models.CharField(blank=True, max_length=4)),
                ("amount_cents", models.BigIntegerField(default=0)),
                ("charged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_charges",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("balance_cents", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("low_balance_threshold_cents", models.BigIntegerField(default=500)),
                ("auto_topup_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("debit", "Debit"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_cents", models.BigIntegerField()),
                ("balance_after_cents", models.BigIntegerField()),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation_charge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="billing.conversationcharge",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversationcharge",
            index=models.Index(
                fields=["organization", "charged_at"],
                name="billing_con_organiz_82fcd9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversationcharge",
            unique_together={("organization", "wa_conversation_id")},
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "-created_at"], name="billing_wal_wallet__e2ecfd_idx"
            ),
        ),
    ]
