# Generated by Django 5.1.15 on 2026-06-22 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial"),
        ("organizations", "0004_alter_organization_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.CharField(
                choices=[("whatsapp", "WhatsApp"), ("sms", "SMS")],
                default="whatsapp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="provider_message_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "channel", "created_at"],
                name="inbox_messa_organiz_c0c130_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["organization", "provider_message_id"],
                name="inbox_messa_organiz_b1b98c_idx",
            ),
        ),
    ]
