# Generated by Django 5.1.15 on 2026-07-01 12:52

from django.db import migrations, models


def deactivate_inbox_bots(apps, schema_editor):
    Conversation = apps.get_model("inbox", "Conversation")
    Conversation.objects.filter(is_bot_active=True).update(is_bot_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0003_message_delivery_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="is_bot_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(deactivate_inbox_bots, migrations.RunPython.noop),
    ]
