# Generated by Django 5.1.15 on 2026-06-13 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFlow',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_trigger', models.CharField(help_text='e.g. hi, hello', max_length=255)),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('any_message', 'Any Message'), ('template_reply', 'Template Reply'), ('button_click', 'Button Click')], default='keyword', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flow_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_flows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BotReply',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reply_type', models.CharField(choices=[('simple', 'Simple Bot Reply'), ('media', 'Media Bot Reply'), ('interactive', 'Advance Interactive Bot Reply')], default='simple', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(blank=True, default=list)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('next_node_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('bot_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='automation.botflow')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='botflow',
            index=models.Index(fields=['organization', 'is_active'], name='automation__organiz_432bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='botflow',
            index=models.Index(fields=['organization', 'start_trigger'], name='automation__organiz_9c58e8_idx'),
        ),
        migrations.AddIndex(
            model_name='botreply',
            index=models.Index(fields=['organization', 'bot_flow', 'reply_type'], name='automation__organiz_5fac87_idx'),
        ),
    ]
