# Generated by Django 5.1.15 on 2026-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_botflow_botreply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='trigger',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('new_message', 'New Message'), ('stage_change', 'Stage Change'), ('tag_added', 'Tag Added'), ('campaign_clicked', 'Campaign Clicked'), ('no_reply', 'No Reply'), ('schedule', 'Schedule'), ('manual', 'Manual')], max_length=30),
        ),
    ]
