# Generated by Django 5.1.15 on 2026-06-13 15:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organization_ai_config_organization_custom_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledPack',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(db_index=True, max_length=100)),
                ('pack_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'pack_id')},
            },
        ),
    ]
