# Generated by Django 5.1.15 on 2026-06-22 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0001_initial"),
        ("organizations", "0004_alter_organization_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True, related_name="groups", to="crm.contact"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="crm_contact_organiz_d9bfa7_idx",
                    ),
                    models.Index(
                        fields=["organization", "category"],
                        name="crm_contact_organiz_f8f631_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="crm_contact_organiz_8d25b0_idx",
                    ),
                ],
                "unique_together": {("organization", "name")},
            },
        ),
    ]
