# Generated by Django 5.1.15 on 2026-06-21 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_alter_organization_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("icon", models.CharField(default="MessageSquare", max_length=50)),
                ("color", models.CharField(default="#3b82f6", max_length=20)),
                ("welcome_message", models.TextField()),
                ("questions", models.JSONField(blank=True, default=list)),
                ("qualify_keywords", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
