# Generated by Django 5.1.15 on 2026-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_ai_config_organization_custom_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent'), ('accountant', 'Accountant'), ('finance', 'Finance User'), ('marketing', 'Marketing'), ('viewer', 'Viewer')], default='agent', max_length=20),
        ),
    ]
