# Generated by Django 5.1.15 on 2026-06-23 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_alter_organization_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("sms", "SMS"),
                    ("email", "Email"),
                    ("other", "Other"),
                ],
                default="whatsapp",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["project_type", "is_active"],
                name="organizatio_project_46517d_idx",
            ),
        ),
    ]
